apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  rules:
  - host: $(URL_HOST)
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik-demo
            port:
              number: 80
