apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-demo
resources:
- source-vars.yaml
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
configMapGenerator:
- name: traefik-demo-config
  env: env.txt
images:
- name: monachus/traefik-demo
  newName: monachus/traefik-demo
  newTag: latest
commonLabels:
  app.kubernetes.io/name: traefik-demo
vars:
- fieldref:
    fieldPath: data.MY_NAMESPACE
  name: MY_NAMESPACE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: source-vars
- fieldref:
    fieldPath: data.URL_HOST
  name: URL_HOST
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: source-vars
configurations:
- kustomize-config.yaml
